#!/usr/bin/env python3
"""Publish GitHub Releases with the GitHub CLI (gh).

  * one release per game: tag game-NNN-v<version>, title "<Name> v<version>",
    assets <Jar>.jar and <Jar>.jad from games/*/dist (built from the tagged commit)
  * milestone releases v0.1.0 ... v0.9.0 tagged at the commit that completed each
    batch of ten games, each with a ZIP rebuilt from that commit in a temporary
    git worktree, and v1.0.0 (all games) with the all-games ZIP

Existing releases are skipped, so the script can be re-run safely.
Run it only after the release commit is pushed. Requires `gh auth login`.

usage: python tools/release.py [--games] [--milestones] [--ids 001 002] [--dry-run]
       (no selection flags = both)
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import catalog  # noqa: E402

ROOT = catalog.ROOT
REPO = catalog.REPO_SLUG
V = catalog.COLLECTION_VERSION

# version, git message that marks the commit, first id, last id
MILESTONES = [
    ("0.1.0", "Add games 001-010", 1, 10),
    ("0.2.0", "Add games 011-020", 11, 20),
    ("0.3.0", "Add games 021-030", 21, 30),
    ("0.4.0", "Add games 031-040", 31, 40),
    ("0.5.0", "Add games 041-050", 41, 50),
    ("0.6.0", "Add games 051-060", 51, 60),
    ("0.7.0", "Add games 069-070", 61, 70),
    ("0.8.0", "Add games 071-080", 71, 80),
    ("0.9.0", "Add games 081-090", 81, 90),
]


def run(cmd, **kw):
    return subprocess.run(cmd, check=True, text=True, capture_output=True, cwd=kw.pop("cwd", ROOT), **kw).stdout


def existing_tags():
    out = run(["gh", "release", "list", "--repo", REPO, "--limit", "500", "--json", "tagName"])
    return {r["tagName"] for r in json.loads(out)}


def head():
    return run(["git", "rev-parse", "HEAD"]).strip()


def game_notes(g):
    controls = "\n".join("| %s | %s |" % (k.replace("|", "/"), v) for k, v in g["controls_list"])
    modes = ("\n**Modes:** %s\n" % ", ".join(g["modes_list"])) if g["modes_list"] else ""
    return """**Game:** {name} (#{id} of the J2ME 100 Games collection)
**Category:** {cat}
**Version:** {ver}

{summary}

{desc}
{modes}
### Controls

| Key | Action |
|---|---|
{controls}
| `*` | Pause menu |

### Supported platforms

* Java ME phones with **MIDP 2.0** and **CLDC 1.0** or later (no floating point, no optional JSRs)
* Emulators such as MicroEmulator, J2ME Loader, KEmulator and FreeJ2ME

### Supported resolutions

128x128, 128x160, 176x208, 176x220, 240x320 (layout adapts at runtime)

### Installation

1. Download **{jar}.jar** below (the `.jad` is only needed for over-the-air installs and some emulators).
2. Copy it to your phone by USB, memory card or Bluetooth, open it and accept the install prompt.
3. Or load it in an emulator.

Full guide: {site}/docs/installing/

### Verification

* Build verified: compiled against the CLDC 1.0 / MIDP 2.0 APIs, JAR + JAD generated by CI
* Automated tests: project reference runtime at 5 resolutions, and a MicroEmulator 2.0.4 smoke test
* **Not yet tested on real phone hardware.** Reports welcome: {repo}/issues/new?template=device-report.yml

Browser demo (TeaVM build of the same source, not the original Java ME version): {site}/games/{slug}/
Source: {repo}/tree/{tag}/games/{folder}
""".format(name=g["name"], id=g["id"], cat=g["category"], ver=g["version"], summary=g["summary"],
           desc=g["description"], modes=modes, controls=controls, jar=g["jar"], site=catalog.PAGES_URL,
           repo=catalog.REPO_URL, slug=g["slug"], tag=g["tag"], folder=g["folder"])


def release_games(games, tags, target, dry):
    made = 0
    for g in games:
        if g["tag"] in tags:
            print("skip %s (exists)" % g["tag"])
            continue
        jar = os.path.join(g["dir"], "dist", g["jar"] + ".jar")
        jad = os.path.join(g["dir"], "dist", g["jar"] + ".jad")
        if not (os.path.exists(jar) and os.path.exists(jad)):
            sys.exit("%s is not built; run tools/build-all.sh first" % g["id"])
        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as f:
            f.write(game_notes(g))
            notes = f.name
        cmd = ["gh", "release", "create", g["tag"], jar, jad, "--repo", REPO, "--target", target,
               "--title", "%s v%s" % (g["name"], g["version"]), "--notes-file", notes, "--latest=false"]
        print(("DRY " if dry else "") + "create " + g["tag"])
        if not dry:
            run(cmd)
            made += 1
        os.unlink(notes)
    return made


def find_commit(message):
    out = run(["git", "log", "--format=%H %s", "--fixed-strings", "--grep", message])
    lines = [l for l in out.splitlines() if l.split(" ", 1)[1].startswith(message)]
    if len(lines) != 1:
        sys.exit("cannot identify the commit for '%s'" % message)
    return lines[0].split(" ")[0]


def build_zip_at(commit, version, first, last, workdir):
    """Check out `commit` in a worktree, build its games first..last and zip them."""
    wt = os.path.join(workdir, "wt-" + version)
    run(["git", "worktree", "add", "--detach", wt, commit])
    try:
        shutil.copytree(os.path.join(ROOT, "tools", "lib"), os.path.join(wt, "tools", "lib"),
                        ignore=shutil.ignore_patterns("microemu"))
        ids = ["%03d" % i for i in range(first, last + 1)]
        py = sys.executable
        subprocess.run([os.path.join(wt, "tools", "ant.cmd" if os.name == "nt" else "ant.sh"), "-q", "-f",
                        os.path.join(wt, "build.xml"), "tools"], check=True, cwd=wt, shell=os.name == "nt")
        subprocess.run([py, os.path.join(wt, "tools", "build_all.py"), "--jobs", "6"] + ids, check=True, cwd=wt)
        zpath = os.path.join(workdir, "j2me-100-games-v%s.zip" % version)
        with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
            for d in sorted(os.listdir(os.path.join(wt, "games"))):
                if not d[:3].isdigit() or not first <= int(d[:3]) <= last:
                    continue
                dist = os.path.join(wt, "games", d, "dist")
                for f in sorted(os.listdir(dist)):
                    if f.endswith((".jar", ".jad")):
                        info = zipfile.ZipInfo("j2me-100-games-v%s/%s" % (version, f), (2026, 1, 1, 0, 0, 0))
                        info.compress_type = zipfile.ZIP_DEFLATED
                        with open(os.path.join(dist, f), "rb") as fh:
                            z.writestr(info, fh.read())
            info = zipfile.ZipInfo("j2me-100-games-v%s/LICENSE" % version, (2026, 1, 1, 0, 0, 0))
            with open(os.path.join(wt, "LICENSE"), "rb") as fh:
                z.writestr(info, fh.read())
        return zpath
    finally:
        run(["git", "worktree", "remove", "--force", wt])


def milestone_notes(version, first, last, games):
    rows = "\n".join("| %s | [%s](%s) | %s |" % (g["id"], g["name"], catalog.release_url(g), g["category"])
                     for g in games if first <= int(g["id"]) <= last)
    total = last
    return """Milestone **v{v}**: games {a:03d}-{b:03d} ({n} games in the collection at this point).

| # | Game | Category |
|---|---|---|
{rows}

The attached ZIP was built from this tag's source and contains the JAR and JAD of games {a:03d}-{b:03d}.
Later fixes are in the per-game releases and in v{latest}.

Verification at the time of this milestone: build verified and tested on the project's reference runtime at five
resolutions. Not tested on real phone hardware.
""".format(v=version, a=first, b=last, n=total, rows=rows, latest=V)


def release_milestones(games, tags, target, dry):
    made = 0
    with tempfile.TemporaryDirectory(prefix="j2me-rel") as work:
        for version, msg, first, last in MILESTONES:
            tag = "v" + version
            if tag in tags:
                print("skip %s (exists)" % tag)
                continue
            commit = find_commit(msg)
            print("milestone %s at %s: building games %03d-%03d" % (tag, commit[:8], first, last))
            if dry:
                continue
            zpath = build_zip_at(commit, version, first, last, work)
            notes = os.path.join(work, tag + ".md")
            with open(notes, "w", encoding="utf-8") as f:
                f.write(milestone_notes(version, first, last, games))
            run(["gh", "release", "create", tag, zpath, "--repo", REPO, "--target", commit,
                 "--title", "v%s - Games %03d-%03d" % (version, first, last), "--notes-file", notes, "--latest=false"])
            made += 1
        tag = "v" + V
        if tag in tags:
            print("skip %s (exists)" % tag)
            return made
        zpath = os.path.join(ROOT, "release", "j2me-100-games-v%s.zip" % V)
        if not os.path.exists(zpath):
            sys.exit("missing %s; run tools/package.sh first" % zpath)
        n = len(games)
        notes = os.path.join(work, tag + ".md")
        with open(notes, "w", encoding="utf-8") as f:
            f.write("""**J2ME 100 Games v{v}: {n} original games for Java ME button phones.**

The attached ZIP contains the JAR and JAD of all {n} games, the license, the README and the install guide.
Every game also has its own release with its JAR and JAD (tags `game-NNN-v{v}`).

* Website and browser demos: {site}
* Install guide: {site}/docs/installing/
* Download list: {site}/download/

### Verification

| Level | Games |
|---|---|
| Build verified (CLDC 1.0 / MIDP 2.0 API, JAR + JAD) | {n} / {n} |
| Reference runtime, 5 resolutions | {n} / {n} |
| MicroEmulator 2.0.4 smoke test | {n} / {n} |
| Real device verified | 0 / {n} |

No game has been tested on real phone hardware yet. Device reports are very welcome:
{repo}/issues/new?template=device-report.yml
""".format(v=V, n=n, site=catalog.PAGES_URL, repo=catalog.REPO_URL))
        print(("DRY " if dry else "") + "create " + tag)
        if not dry:
            run(["gh", "release", "create", tag, zpath, "--repo", REPO, "--target", target,
                 "--title", "v%s - %d Games" % (V, n), "--notes-file", notes, "--latest"])
            made += 1
    return made


def write_report():
    out = json.loads(run(["gh", "release", "list", "--repo", REPO, "--limit", "500", "--json", "tagName"]))
    tags = [r["tagName"] for r in out]
    rep = {"game_releases": sum(1 for t in tags if t.startswith("game-")),
           "milestone_releases": sum(1 for t in tags if t.startswith("v")),
           "tags": sorted(tags)}
    with open(os.path.join(ROOT, "reports", "release-report.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(rep, f, indent=1)
        f.write("\n")
    print("releases on GitHub: %d per-game, %d milestone" % (rep["game_releases"], rep["milestone_releases"]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", action="store_true")
    ap.add_argument("--milestones", action="store_true")
    ap.add_argument("--ids", nargs="*")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    both = not a.games and not a.milestones
    games = catalog.load_games()
    if a.ids:
        games_sel = [g for g in games if g["id"] in a.ids]
    else:
        games_sel = games
    if run(["git", "status", "--porcelain", "--untracked-files=no"]).strip():
        sys.exit("working tree has uncommitted changes; commit and push first")
    target = head()
    remote = run(["git", "ls-remote", "origin", "refs/heads/main"]).split()
    if not remote or remote[0] != target:
        sys.exit("HEAD %s is not what origin/main points to; push first" % target[:8])
    tags = existing_tags()
    made = 0
    if a.games or both:
        made += release_games(games_sel, tags, target, a.dry_run)
    if a.milestones or both:
        made += release_milestones(games, tags, target, a.dry_run)
    print("created %d releases" % made)
    if not a.dry_run:
        write_report()


if __name__ == "__main__":
    main()
