package lasermirrors;

import gamekit.Game;
import gamekit.Gfx;
import gamekit.Rnd;
import gamekit.Sfx;
import javax.microedition.lcdui.Graphics;

/**
 * Laser Mirrors: rotate mirrors so a laser beam lights every target crystal.
 * Puzzles are generated by walking a random beam path, placing mirrors at
 * its turns and targets along it, then scrambling the mirrors.
 */
public class LaserGame extends Game {
    private static final int N = 7, LEVELS = 15;
    private static final int EMPTY = 0, SLASH = 1, BACK = 2, WALL = 3;

    private final int[][] cell = new int[N][N];
    private final boolean[][] target = new boolean[N][N], lit = new boolean[N][N], fixed = new boolean[N][N];
    private final int[] beamR = new int[N * N * 4 + 2], beamC = new int[N * N * 4 + 2];
    private int beamN, emR, level, cr, cc, moves, targets, litCount, clearT;
    private boolean beamOut;

    protected String name() { return "Laser Mirrors"; }

    protected String[] help() {
        return new String[] {
            "A laser fires from the left wall. Rotate the mirrors so the beam bounces through every crystal on the board.",
            "Mirrors flip between / and \\. Grey blocks stop the beam, and some mirrors are bolted in place (shown with a dot).",
            "Clear 15 puzzles. Fewer rotations score more points.",
            "- Controls",
            "2/4/6/8: move cursor",
            "5: rotate mirror",
            "0: reset puzzle",
        };
    }

    protected int accent() { return 0xFF1744; }

    protected void newGame() {
        level = 0;
        nextLevel();
    }

    private final int[][] start = new int[N][N];

    private void nextLevel() {
        level++;
        generate();
        cr = emR;
        cc = 0;
        moves = 0;
        clearT = 0;
        trace();
    }

    private void generate() {
        int turns = Math.min(6, 2 + level / 3);
        int nTargets = Math.min(4, 1 + (level + 1) / 4);
        for (int attempt = 0; attempt < 200; attempt++) {
            for (int r = 0; r < N; r++) for (int c = 0; c < N; c++) {
                cell[r][c] = EMPTY;
                target[r][c] = false;
                fixed[r][c] = false;
            }
            boolean[][] seen = new boolean[N][N];
            emR = Rnd.nextInt(N);
            int r = emR, c = -1, dr = 0, dc = 1, made = 0;
            int pathN = 0;
            int[] pr = new int[N * N], pc = new int[N * N];
            while (true) {
                int nr = r + dr, nc = c + dc;
                if (nr < 0 || nr >= N || nc < 0 || nc >= N) break;
                if (cell[nr][nc] != EMPTY) break;
                r = nr;
                c = nc;
                boolean fresh = !seen[r][c];
                if (fresh) { pr[pathN] = r; pc[pathN++] = c; }
                seen[r][c] = true;
                if (made < turns && Rnd.chance(40)) {
                    int type = Rnd.chance(50) ? SLASH : BACK;
                    // only turn on cells the beam has crossed once (so it is not crossed again later)
                    int ndr = type == SLASH ? -dc : dc, ndc = type == SLASH ? -dr : dr;
                    int tr = r + ndr, tc = c + ndc;
                    if (fresh && tr >= 0 && tr < N && tc >= 0 && tc < N && !seen[tr][tc]) {
                        cell[r][c] = type;
                        dr = ndr;
                        dc = ndc;
                        made++;
                        pathN--; // mirror cells are not target candidates
                    }
                }
            }
            if (made < turns) continue;
            int placed = 0;
            for (int k = 0; k < nTargets * 4 && placed < nTargets; k++) {
                int i = k == 0 ? pathN - 1 : Rnd.nextInt(pathN);
                if (i < 0 || cell[pr[i]][pc[i]] != EMPTY || target[pr[i]][pc[i]]) continue;
                target[pr[i]][pc[i]] = true;
                placed++;
            }
            if (placed < nTargets) continue;
            targets = placed;
            trace();
            if (litCount != targets) continue;
            // decoys
            int walls = level / 2, decoys = level / 3;
            for (int k = 0; k < 40 && (walls > 0 || decoys > 0); k++) {
                int wr = Rnd.nextInt(N), wc = Rnd.nextInt(N);
                if (cell[wr][wc] != EMPTY || target[wr][wc] || lit[wr][wc]) continue;
                if (walls > 0) { cell[wr][wc] = WALL; walls--; }
                else { cell[wr][wc] = Rnd.chance(50) ? SLASH : BACK; decoys--; }
            }
            // bolt a couple of mirrors in place, scramble the rest
            int scrambled = 0;
            for (int a = 0; a < N; a++) for (int b = 0; b < N; b++) {
                if (cell[a][b] != SLASH && cell[a][b] != BACK) continue;
                if (level > 4 && Rnd.chance(15)) { fixed[a][b] = true; continue; }
                if (Rnd.chance(65)) { cell[a][b] = 3 - cell[a][b]; scrambled++; }
            }
            trace();
            if (scrambled == 0 || litCount == targets) continue;
            for (int a = 0; a < N; a++) for (int b = 0; b < N; b++) start[a][b] = cell[a][b];
            return;
        }
        // fallback: trivial straight shot
        for (int r = 0; r < N; r++) for (int c = 0; c < N; c++) { cell[r][c] = EMPTY; target[r][c] = false; start[r][c] = EMPTY; }
        emR = N / 2;
        target[emR][N - 1] = true;
        targets = 1;
    }

    private void trace() {
        for (int r = 0; r < N; r++) for (int c = 0; c < N; c++) lit[r][c] = false;
        int r = emR, c = -1, dr = 0, dc = 1;
        beamN = 0;
        beamR[beamN] = r;
        beamC[beamN++] = c;
        beamOut = false;
        for (int step = 0; step < N * N * 4; step++) {
            int nr = r + dr, nc = c + dc;
            if (nr < 0 || nr >= N || nc < 0 || nc >= N) {
                beamR[beamN] = nr;
                beamC[beamN++] = nc;
                beamOut = true;
                break;
            }
            r = nr;
            c = nc;
            lit[r][c] = true;
            int t = cell[r][c];
            if (t == WALL) {
                beamR[beamN] = r;
                beamC[beamN++] = c;
                break;
            }
            if (t == SLASH || t == BACK) {
                beamR[beamN] = r;
                beamC[beamN++] = c;
                int ndr = t == SLASH ? -dc : dc, ndc = t == SLASH ? -dr : dr;
                dr = ndr;
                dc = ndc;
            }
            if (beamN >= beamR.length - 1) break;
        }
        if (!beamOut && beamN < beamR.length && (beamR[beamN - 1] != r || beamC[beamN - 1] != c)) {
            beamR[beamN] = r;
            beamC[beamN++] = c;
        }
        litCount = 0;
        for (int a = 0; a < N; a++) for (int b = 0; b < N; b++) if (target[a][b] && lit[a][b]) litCount++;
    }

    protected void update() {
        if (clearT > 0) {
            if (--clearT == 0) {
                if (level >= LEVELS) {
                    headline = "ALL BEAMS ALIGNED";
                    endGame(true);
                } else nextLevel();
            }
            return;
        }
        if ((pressed & K_UP) != 0) cr = (cr + N - 1) % N;
        if ((pressed & K_DOWN) != 0) cr = (cr + 1) % N;
        if ((pressed & K_LEFT) != 0) cc = (cc + N - 1) % N;
        if ((pressed & K_RIGHT) != 0) cc = (cc + 1) % N;
        if ((pressed & K_FIRE) != 0) {
            int t = cell[cr][cc];
            if ((t == SLASH || t == BACK) && !fixed[cr][cc]) {
                cell[cr][cc] = 3 - t;
                moves++;
                Sfx.click();
                trace();
                if (litCount == targets) {
                    score += 100 + Math.max(0, 60 - moves * 4) + level * 10;
                    clearT = 25;
                    Sfx.win();
                }
            } else Sfx.bad();
        }
        if (digit(0)) {
            for (int a = 0; a < N; a++) for (int b = 0; b < N; b++) cell[a][b] = start[a][b];
            moves = 0;
            trace();
        }
    }

    protected void draw(Graphics g) {
        int hud = Gfx.SMALL.getHeight() + 2;
        int s = Math.min((W - 8) / (N + 1), (H - hud * 2 - 4) / N);
        int ox = (W - s * N) / 2 + s / 2, oy = hud + (H - hud * 2 - s * N) / 2;
        g.setColor(0x0B0F1A);
        g.fillRect(0, 0, W, H);
        for (int r = 0; r < N; r++) for (int c = 0; c < N; c++) {
            int x = ox + c * s, y = oy + r * s;
            g.setColor((r + c) % 2 == 0 ? 0x1A2236 : 0x161D2E);
            g.fillRect(x, y, s, s);
            int t = cell[r][c];
            if (t == WALL) {
                Gfx.bevel(g, x + 1, y + 1, s - 2, s - 2, 0x607D8B);
            } else if (t == SLASH || t == BACK) {
                g.setColor(fixed[r][c] ? 0x90A4AE : 0xE0F7FA);
                int m = 2;
                if (t == SLASH) {
                    g.drawLine(x + m, y + s - 1 - m, x + s - 1 - m, y + m);
                    g.drawLine(x + m + 1, y + s - 1 - m, x + s - 1 - m, y + m + 1);
                } else {
                    g.drawLine(x + m, y + m, x + s - 1 - m, y + s - 1 - m);
                    g.drawLine(x + m + 1, y + m, x + s - 1 - m, y + s - 2 - m);
                }
                if (fixed[r][c]) {
                    g.setColor(0xFFB300);
                    g.fillRect(x + s / 2 - 1, y + s / 2 - 1, 2, 2);
                }
            }
            if (target[r][c]) {
                int cx = x + s / 2, cy = y + s / 2, k = s / 3;
                g.setColor(lit[r][c] ? 0x76FF03 : 0x2E7D32);
                g.fillTriangle(cx, cy - k, cx - k, cy, cx + k, cy);
                g.fillTriangle(cx, cy + k, cx - k, cy, cx + k, cy);
            }
        }
        // emitter
        g.setColor(0xFF1744);
        g.fillRect(ox - s / 2, oy + emR * s + s / 4, s / 2, s / 2);
        // beam
        int pulse = (clock & 2) == 0 ? 0xFF5252 : 0xFF1744;
        g.setColor(clearT > 0 ? 0x76FF03 : pulse);
        for (int i = 1; i < beamN; i++) {
            int x0 = ox + beamC[i - 1] * s + s / 2, y0 = oy + beamR[i - 1] * s + s / 2;
            int x1 = ox + beamC[i] * s + s / 2, y1 = oy + beamR[i] * s + s / 2;
            if (i == 1) x0 = ox;
            g.drawLine(x0, y0, x1, y1);
            if (x0 == x1) g.drawLine(x0 + 1, y0, x1 + 1, y1);
            else g.drawLine(x0, y0 + 1, x1, y1 + 1);
        }
        // cursor
        g.setColor(0xFFEB3B);
        g.drawRect(ox + cc * s, oy + cr * s, s - 1, s - 1);
        g.setFont(Gfx.SMALL_B);
        g.setColor(0xFFFFFF);
        g.drawString("Puzzle " + level + "/" + LEVELS, 2, 1, Gfx.TL);
        g.setColor(0x76FF03);
        g.drawString(litCount + "/" + targets, W - 2, 1, Gfx.TR);
        Gfx.text(g, clearT > 0 ? "Aligned!" : "Turns " + moves + "   0: reset", W / 2, H - hud + 1, Gfx.TC, Gfx.SMALL, 0x90A4AE);
    }

    protected void drawTitleArt(Graphics g, int x, int y, int w, int h) {
        int my = y + h / 2, mx = x + w / 2;
        g.setColor(0xFF1744);
        g.fillRect(x, my - 2, 6, 4);
        int t = clock % 40;
        int up = t < 20 ? 1 : -1;
        g.drawLine(x + 6, my, mx, my);
        g.drawLine(mx, my, mx + h / 2, my - up * (h / 2 - 2));
        g.setColor(0xE0F7FA);
        if (up == 1) g.drawLine(mx - 5, my + 5, mx + 5, my - 5);
        else g.drawLine(mx - 5, my - 5, mx + 5, my + 5);
        g.setColor(0x76FF03);
        int ex = mx + h / 2, ey = my - up * (h / 2 - 2);
        g.fillTriangle(ex, ey - 4, ex - 4, ey, ex + 4, ey);
        g.fillTriangle(ex, ey + 4, ex - 4, ey, ex + 4, ey);
    }
}
